"""
Django settings for work_flow project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
import warnings
from datetime import timedelta
from pathlib import Path

from django.core.cache import CacheKeyWarning
from django.views.decorators.cache import cache_page

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
HOST_URL = os.environ.get("HOST_URL", "")
os.environ.setdefault('E_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [os.environ.get("E_ALLOWED_HOSTS")]

os.environ.setdefault('E_FLOWER_HOST', '127.0.0.1')
os.environ.setdefault('E_FLOWER_PORT', '5555')

CELERY_TASK_HANDLERS = []

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test' or 'pytest' in sys.argv[0]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'corsheaders',
    'colorfield',
    'django_json_widget',
    'mptt',
    'nested_admin',
    'django_ckeditor_5',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'notifications',
    'project',
    'sprint',
    'work',
    'permissions',
    'comments',
    'references',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'work_flow.urls'

CORS_ALLOW_ALL_ORIGINS = True
REST_USE_JWT = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'work_flow.wsgi.application'

ASGI_APPLICATION = 'work_flow.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(f"{os.environ.get('E_REDIS_HOST')}", os.environ.get("E_REDIS_PORT"))],
        },
    },
}

AUTH_USER_MODEL = "users.UserExtended"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'utils.default_paginator.DefaultRestPaginator',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser'
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,          # при обновлении токена старый refresh уходит в черный список
    'BLACKLIST_AFTER_ROTATION': True,       # старые токены добавляются в черный список
    'UPDATE_LAST_LOGIN': False,
    # 'AUTH_HEADER_TYPES': ('Bearer',),
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get("E_DB_DATABASE"),
        'USER': os.environ.get("E_DB_USER"),
        'PASSWORD': os.environ.get("E_DB_PASSWORD"),
        'HOST': os.environ.get("E_DB_ADDRESS"),
        'PORT': os.environ.get("E_DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

if os.path.exists('Version.txt'):
    with open('Version.txt') as version_file:
        STATIC_VERSION = version_file.readline().rstrip()
else:
    STATIC_VERSION = ''

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'v{}'.format(STATIC_VERSION))

STATIC_URL = '/static/v{}/'.format(STATIC_VERSION)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

os.environ.setdefault('E_REDIS_HOST', 'localhost')
os.environ.setdefault('E_REDIS_PORT', '6379')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER', '')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER_1', '1')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER_2', '2')

# настройка отправки писем
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL") == "True"
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CELERY_BROKER_URL = f'redis://{os.environ.get("E_REDIS_HOST")}:{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}'  # noqa
CELERY_RESULT_BACKEND = f'redis://{os.environ.get("E_REDIS_HOST")}:{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}'  # noqa
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE

CACHES = {
    # Кэш по умолчанию
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    },
    # Кэш для Singleton (кэшируем настройки в redis)
    "settings": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "settings_cache"
    },
    # Кэш для viewset
    "viewset": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "viewset_cache"
    },
    # Кэширование методов и функций
    "method_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_1")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "method_cache"
    },
    # Кэш блокировки заданий celery
    "lock_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_1")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "lock_cache"
    },
    "licences_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_2")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "licences_cache"
    }
}

# Режим работы при котором ключи в redis являются контрольными суммами
CACHEOPS_INSIDEOUT = True

# Если проблема с редисом - не используем кэширование
CACHEOPS_DEGRADE_ON_FAILURE = True

# Кэшируем по умолчанию на час
CACHEOPS_DEFAULTS = {
    'timeout': 60 * 60
}

# Подключение к redis для cacheops
CACHEOPS_REDIS = f'redis://{os.environ.get("E_REDIS_HOST")}:' \
                 f'{os.environ.get("E_REDIS_PORT")}/' \
                 f'{int(os.environ.get("E_REDIS_DB_IDENTIFIER_1")) + 1}'

CACHEOPS = {
    # Автоматически кешировать все объекты user на 1 минуту
    'auth.user': {'ops': 'all', 'timeout': 60},

    # Автоматически кешировать все запросы .count()
    # для оставшихся моделей на 2 минуты
    '*.*': {'ops': ('count',), 'timeout': 60 * 2},
}

# Переопределяется в local_settings чтобы отключить кэширование для режима разработки - мало
# переопределить CACHES, надо еще позаботиться о заголовке Expires, чтобы избежать кэширования браузером
CACHE_FUNC = cache_page
warnings.simplefilter("ignore", CacheKeyWarning)

SOLO_CACHE = 'settings'
SOLO_CACHE_TIMEOUT = 60

METHOD_CACHE = 'method_cache'

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                    }

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3', '|', 'bulletedList', 'numberedList', '|', 'blockQuote',
        ],
        'toolbar': {
            'items': [
                'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                'insertTable',
            ],
            'shouldNotGroupWhenFull': 'true',
        },
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # Possible values: "staff", "authenticated", "any"
