"""
Django settings for work_flow project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
import warnings
from datetime import timedelta
from pathlib import Path

from django.core.cache import CacheKeyWarning
from django.views.decorators.cache import cache_page

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
HOST_URL = os.environ.get("HOST_URL", "")
os.environ.setdefault('E_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [os.environ.get("E_ALLOWED_HOSTS")]

os.environ.setdefault('E_FLOWER_HOST', '127.0.0.1')
os.environ.setdefault('E_FLOWER_PORT', '5555')

CELERY_TASK_HANDLERS = []

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test' or 'pytest' in sys.argv[0]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'work_flow.urls'

CORS_ALLOW_ALL_ORIGINS = True
REST_USE_JWT = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'work_flow.wsgi.application'

ASGI_APPLICATION = 'work_flow.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(f"{os.environ.get('E_REDIS_HOST')}", os.environ.get("E_REDIS_PORT"))],
        },
    },
}

AUTH_USER_MODEL = "users.UserExtended"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'utils.default_paginator.DefaultRestPaginator',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser'
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,          # при обновлении токена старый refresh уходит в черный список
    'BLACKLIST_AFTER_ROTATION': True,       # старые токены добавляются в черный список
    'UPDATE_LAST_LOGIN': False,
    # 'AUTH_HEADER_TYPES': ('Bearer',),
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get("E_DB_DATABASE"),
        'USER': os.environ.get("E_DB_USER"),
        'PASSWORD': os.environ.get("E_DB_PASSWORD"),
        'HOST': os.environ.get("E_DB_ADDRESS"),
        'PORT': os.environ.get("E_DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

if os.path.exists('Version.txt'):
    with open('Version.txt') as version_file:
        STATIC_VERSION = version_file.readline().rstrip()
else:
    STATIC_VERSION = ''

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'v{}'.format(STATIC_VERSION))

STATIC_URL = '/static/v{}/'.format(STATIC_VERSION)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

os.environ.setdefault('E_REDIS_HOST', 'localhost')
os.environ.setdefault('E_REDIS_PORT', '6379')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER', '')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER_1', '1')
os.environ.setdefault('E_REDIS_DB_IDENTIFIER_2', '2')

CELERY_BROKER_URL = f'redis://{os.environ.get("E_REDIS_HOST")}:{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}'  # noqa
CELERY_RESULT_BACKEND = f'redis://{os.environ.get("E_REDIS_HOST")}:{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}'  # noqa
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE

CACHES = {
    # Кэш по умолчанию
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    },
    # Кэш для Singleton (кэшируем настройки в redis)
    "settings": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "settings_cache"
    },
    # Кэш для viewset
    "viewset": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "viewset_cache"
    },
    # Кэширование методов и функций
    "method_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_1")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "method_cache"
    },
    # Кэш блокировки заданий celery
    "lock_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_1")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "lock_cache"
    },
    "licences_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("E_REDIS_HOST")}:'
                    f'{os.environ.get("E_REDIS_PORT")}/{os.environ.get("E_REDIS_DB_IDENTIFIER_2")}',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "licences_cache"
    }
}

# Режим работы при котором ключи в redis являются контрольными суммами
CACHEOPS_INSIDEOUT = True

# Если проблема с редисом - не используем кэширование
CACHEOPS_DEGRADE_ON_FAILURE = True

# Кэшируем по умолчанию на час
CACHEOPS_DEFAULTS = {
    'timeout': 60 * 60
}

# Подключение к redis для cacheops
CACHEOPS_REDIS = f'redis://{os.environ.get("E_REDIS_HOST")}:' \
                 f'{os.environ.get("E_REDIS_PORT")}/' \
                 f'{int(os.environ.get("E_REDIS_DB_IDENTIFIER_1")) + 1}'

CACHEOPS = {
    # Автоматически кешировать все объекты user на 1 минуту
    'auth.user': {'ops': 'all', 'timeout': 60},

    # Автоматически кешировать все запросы .count()
    # для оставшихся моделей на 2 минуты
    '*.*': {'ops': ('count',), 'timeout': 60 * 2},
}

# Переопределяется в local_settings чтобы отключить кэширование для режима разработки - мало
# переопределить CACHES, надо еще позаботиться о заголовке Expires, чтобы избежать кэширования браузером
CACHE_FUNC = cache_page
warnings.simplefilter("ignore", CacheKeyWarning)

SOLO_CACHE = 'settings'
SOLO_CACHE_TIMEOUT = 60

METHOD_CACHE = 'method_cache'
