# Generated by Django 5.2.1 on 2026-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_active',
            field=models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен'),
        ),
    ]
