# Generated by Django 5.2.1 on 2026-05-06 06:11

import utils.django_validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextended_slug_alter_userextended_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='users/profile_photos', validators=[utils.django_validate.validate_is_image, utils.django_validate.validate_is_image_not_broken, utils.django_validate.validate_image_size], verbose_name='Фотография пользователя'),
        ),
    ]
