# Generated by Django 5.2.1 on 2026-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userextended_birth_date_userextended_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='need_send_email_notification',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отправлять пользователю письма - уведомления'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='need_send_push_notification',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отправлять пользователю пуш - уведомления'),
        ),
    ]
