# Generated by Django 5.2.1 on 2026-05-02 11:33

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('references', '0001_initial'),
        ('sprint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('target_start_date', models.DateField(blank=True, null=True, verbose_name='Необходимо начать с')),
                ('target_end_date', models.DateField(blank=True, null=True, verbose_name='Необходимо закончить до')),
                ('lead_time', models.DurationField(blank=True, null=True, verbose_name='Первоначальная оценка времени выполнения')),
                ('wasted_time', models.DurationField(blank=True, null=True, verbose_name='Времени потрачено на выполнение')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Код (slug) работы')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='references.workdifficulty', verbose_name='Сложность')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_works', to='work.work', verbose_name='Эпик')),
                ('execute_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works_executed', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('histories', models.ManyToManyField(blank=True, related_name='history_works', to='work.work', verbose_name='Истории')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='references.workpriority', verbose_name='Приоритет')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='project.project', verbose_name='Проект')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='sprint.sprint', verbose_name='Спринт')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='project.projectstatus', verbose_name='Статус')),
                ('tags', models.ManyToManyField(blank=True, related_name='works', to='references.worktag', verbose_name='Теги')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='references.worktechnology', verbose_name='Технология')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='references.worktype', verbose_name='Тип работы')),
                ('versions', models.ManyToManyField(blank=True, related_name='works', to='project.projectversion', verbose_name='Версии')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('is_blocked_by', 'Заблокирован задачей'), ('blocks', 'Блокирует задачу'), ('clones', 'Клон задачи'), ('is_cloned_by', 'Клонирован от задачи'), ('duplicates', 'Дублирует задачу'), ('is_duplicated_by', 'Дублирован от задачи'), ('has_to_be_finished_together_with', 'Завершить вместе с задачей'), ('has_to_be_done_before', 'Нужно сделать до выполнения задачи'), ('has_to_be_done_after', 'Нужно сделать после выполнения задачи'), ('has_to_be_started_together_with', 'Начать вместе с задачей'), ('relates_to', 'Связана с задачей'), ('is_parent_task_of', 'Является родительской для задачи'), ('is_subtask_of', 'Является дочерней от задачи'), ('causes', 'Является причиной для задачи'), ('is_caused_by', 'Вызвана от задачи')], max_length=50, verbose_name='Тип связи')),
                ('work_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='work.work', verbose_name='Прикрепляемая работа')),
                ('work_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='work.work', verbose_name='Работа, к которой прикрепляем')),
            ],
            options={
                'verbose_name': 'Связь работы',
                'verbose_name_plural': 'Связи работ',
            },
        ),
    ]
