# Generated by Django 5.2.1 on 2026-05-02 02:28

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations, models, connection


def set_default_objects(apps, schema_editor):
    from utils.choices.default_work_types_choices import DefaultWorkTypes
    WorkType = apps.get_model("references", "WorkType")

    for row in [
        {
            'id': choice.value,
            'is_system': True,
            'name': choice.label,
            'slug': choice.slug,
            'description': f'Создано автоматически — не изменять и не удалять. {choice.description}',
            'color': choice.color,
        } for choice in DefaultWorkTypes
    ]:
        WorkType.objects.create(**row)

    # FIX SEQUENCE
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('references_worktype', 'id'),
                (SELECT MAX(id) FROM references_worktype)
            );
            """
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='WorkDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложностей',
            },
        ),
        migrations.CreateModel(
            name='WorkPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Приоритет работы',
                'verbose_name_plural': 'Приоритеты работ',
            },
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Тэг работы',
                'verbose_name_plural': 'Тэги работ',
            },
        ),
        migrations.CreateModel(
            name='WorkTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Технология работы',
                'verbose_name_plural': 'Технологии работ',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активен')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Изображение/иконка')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (URL) записи')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, help_text='Оставьте пустым для случайного выбора цвета', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.RunPython(set_default_objects, migrations.RunPython.noop),
    ]
